sources:
  repo:
    type: codeup
    name: "{{projectName}}"
    endpoint: "{{repoUrl}}"
    branch: master
    triggerEvents: push
    certificate:
      type: serviceConnection
      serviceConnection: "{{serviceConnectionId}}"
stages:
  build_stage:
    name: "Build"
    jobs:
      build_job:
        name: "Build and upload to OSS"
        runsOn:
          group: "{{runnerGroup}}"
          container: "{{container}}"
        steps:
          build_step:
            name: "Build"
            step: "Command"
            with:
              run: |
                {{buildCommand}}
          upload_step:
            name: "Upload to OSS"
            step: "Command"
            with:
              run: |
                ossutil cp -r -f {{artifactDir}}/ oss://{{bucket}}/
